MM1_STEERING_MID = 1550
MM1_MAX_FORWARD = 1620  # Max is 2000
MM1_MAX_REVERSE = 1350
MM1_STOPPED_PWM = 1500
MM1_SHOW_STEERING_VALUE = False
MM1_SERIAL_PORT = '/dev/ttyS0'

THROTTLE_FORWARD_PWM = 395
THROTTLE_STOPPED_PWM = 370  # pwm value for no movement
THROTTLE_REVERSE_PWM = 340

STEERING_LEFT_PWM = 510 # pwm value for full left steering
STEERING_RIGHT_PWM = 290

# SERVO_ESC|DC_STEER_THROTTLE|DC_TWO_WHEEL|DC_TWO_WHEEL_L298N|SERVO_HBRIDGE_PWM|PIGPIO_PWM|MM1|MOCK
DRIVE_TRAIN_TYPE = "PIGPIO_PWM"

JOYSTICK_MAX_THROTTLE = 1.0
JOYSTICK_THROTTLE_DIR = -1.0

CONTROLLER_TYPE = 'F710'  # (ps3|ps4)
DRIVE_LOOP_HZ = 30

if CONTROLLER_TYPE == 'F710':
    JOYSTICK_DEADZONE = 0.1

AUTO_CREATE_NEW_TUB = True
MAX_EPOCHS = 30

USE_SSD1306_128_32 = True  # Enable the SSD_1306 OLED Display

# DONKEY_GYM = True
# DONKEY_SIM_PATH = "remote"
# SIM_HOST="192.168.1.238"
IMAGE_W = 640
IMAGE_H = 480
CAMERA_TYPE = "PICAM"

USE_CUSTOM_CONTROLLER = True
